---
# Role: common
# File: tasks/main.yml
- name: disable the http_proxy configuration
  copy: src="proxy.sh" dest="/etc/profile.d/proxy.sh"
    owner="root" group="root" mode=0644
  tags: disable_proxy

- name: be sure YUM is configured
  copy: src="yum.conf" dest="/etc/yum.conf"
    owner="root" group="root" mode=0644
  tags:
    - repo
    - yum

- name: be sure the EPEL repository is enabled
  yum:
    name: epel-release
    state: installed
  tags: repo

- name: be sure ntp is installed
  yum:
    name: ntp
    state: installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest="/etc/ntp.conf"
    owner="root" group="root" mode=0644
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags:
    - ntp
